import { ScanResult } from '../models/ScanResult';
import { Finding, Severity } from '../models/Finding';

export class MarkdownReporter {
  generate(result: ScanResult): string {
    const lines: string[] = [];
    
    lines.push('# Lui Security Report');
    lines.push('');
    lines.push('---');
    lines.push('');
    lines.push('## Overview');
    lines.push('');
    lines.push(`| Property | Value |`);
    lines.push(`|----------|-------|`);
    lines.push(`| Target | \`${result.target}\` |`);
    lines.push(`| Scan Type | ${result.scanType} |`);
    lines.push(`| Date | ${result.scanDate} |`);
    lines.push(`| Duration | ${(result.duration / 1000).toFixed(1)}s |`);
    lines.push(`| Score | **${result.score}/100** (${result.scoreLabel}) |`);
    lines.push('');
    
    // Technology
    const tech = result.technologyProfile;
    if (tech.languages.length > 0 || tech.frameworks.length > 0) {
      lines.push('## Technology Profile');
      lines.push('');
      if (tech.languages.length > 0) lines.push(`- **Languages:** ${tech.languages.join(', ')}`);
      if (tech.frameworks.length > 0) lines.push(`- **Frameworks:** ${tech.frameworks.join(', ')}`);
      if (tech.databases.length > 0) lines.push(`- **Databases:** ${tech.databases.join(', ')}`);
      if (tech.deployment.length > 0) lines.push(`- **Deployment:** ${tech.deployment.join(', ')}`);
      lines.push('');
    }
    
    // Summary
    lines.push('## Security Summary');
    lines.push('');
    const { summary } = result;
    lines.push(`| Severity | Count |`);
    lines.push(`|----------|-------|`);
    lines.push(`| CRITICAL | ${summary.CRITICAL} |`);
    lines.push(`| HIGH | ${summary.HIGH} |`);
    lines.push(`| MEDIUM | ${summary.MEDIUM} |`);
    lines.push(`| LOW | ${summary.LOW} |`);
    lines.push(`| INFO | ${summary.INFO} |`);
    lines.push('');
    
    // Findings by severity
    const severities: Severity[] = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO'];
    for (const severity of severities) {
      const findings = result.findings.filter(f => f.severity === severity && f.status !== 'suppressed');
      if (findings.length === 0) continue;
      
      lines.push(`## ${severity} Findings`);
      lines.push('');
      
      for (const finding of findings) {
        lines.push(`### ${finding.id}: ${finding.title}`);
        lines.push('');
        lines.push(`- **Confidence:** ${finding.confidence}`);
        lines.push(`- **Category:** ${finding.category}`);
        lines.push(`- **CWE:** ${finding.cwe || 'N/A'}`);
        lines.push('');
        
        if (finding.affectedFiles.length > 0) {
          lines.push('**Location:**');
          for (const file of finding.affectedFiles) {
            lines.push(`- \`${file.file}${file.line ? ':' + file.line : ''}\``);
          }
          lines.push('');
        }
        
        lines.push('**Description:**');
        lines.push(finding.description);
        lines.push('');
        
        lines.push('**Impact:**');
        lines.push(finding.impact);
        lines.push('');
        
        lines.push('**Recommendation:**');
        lines.push(finding.recommendation);
        lines.push('');
        
        if (finding.evidence.length > 0) {
          lines.push('**Evidence:**');
          for (const ev of finding.evidence) {
            lines.push(`- \`${ev}\``);
          }
          lines.push('');
        }
        
        lines.push('---');
        lines.push('');
      }
    }
    
    // Footer
    lines.push('');
    lines.push('*Report generated by Lui Security Auditor v0.1.0*');
    
    return lines.join('\n');
  }
}
